---
- name: apt update
  apt:
    update_cache: yes

- name: Install Nginx and PHP 7 FPM
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nginx
    - php7.0-fpm

- name: Template for Nginx
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Clean sites-enabled 
  file:
    state: absent
    path: /etc/nginx/sites-enabled/

- name: Creates directory "{{ site_path }}"
  file:
    path: "/{{ site_path }}"
    state: directory

- name: copy site to path "{{ site_path }}"
  copy:
    src: index.php
    dest: "/{{ site_path }}/index.php"
  notify:
   - Restart Nginx
