---
- name: apt update
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nginx
    - lsb-release
    - apt-transport-https
    - ca-certificates

- name: Download gpg key
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: add dep repository php7.3
  shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" >> /etc/apt/sources.list.d/php7.3.list

- name: Update repositories cache and install PHP7.3-fpm package
  apt:
    name: php7.3-fpm
    update_cache: yes

- name: Template for Nginx
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Clean sites-enabled 
  file:
    state: absent
    path: /etc/nginx/sites-enabled/

- name: Creates directory "{{ site_path }}"
  file:
    path: "/{{ site_path }}"
    state: directory

- name: copy site to path "{{ site_path }}"
  copy:
    src: index.php
    dest: "/{{ site_path }}/index.php"
  notify:
   - Restart Nginx
